import datetime
ob=datetime.datetime.now()
print(type(ob))
print('-'*25)
print(ob)
print(ob.month)
print(ob.year)
print(ob.day)
print(ob.hour)
print(ob.minute)
print(ob.second)
str1=str(ob.hour)+':'+str(ob.minute)+':'+str(ob.second)
print(str1)
print("-"*25)
print("1 week ago it was:",ob - datetime.timedelta(weeks=1))
print("hunbdred days ago it was:",ob-datetime.timedelta(days=100))
print("i week from it will be:",ob+datetime.timedelta(weeks=1))
print("thousand days ago it was:",ob+datetime.timedelta(days=1000))
bday_sunilk=datetime.datetime(200,1,16)
print("bday in ",ob - bday_sunilk)
print("-"*25)

